# Generated by Django 5.0.3 on 2024-04-02 23:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='date',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.CharField(max_length=100),
        ),
    ]
