# Generated by Django 5.0.3 on 2024-04-03 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_remove_medicalrecord_date_medicalrecord_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
