# Generated by Django 5.0.3 on 2024-06-05 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_medicalrecord_date_medicalrecord_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
